package com.landalytics.model.epc.clean

import com.landalytics.utilities.addressparsers.ParsedAddressModel.ParsedAddress

import java.sql.Date

object CleanEPCModel {

  case class EPC(
                lmkKey: String,
                fullAddress: String,
                parsedAddress: ParsedAddress,
                epcDetails: EPCDetails,
                uprn: Option[String],
                uprnSource: Option[String]
                )

  case class EPCSlim(
                      lmkKey: String,
                      fullAddress: String,
                      parsedAddress: ParsedAddress,
                      uprn: Option[String],
                      uprnSource: Option[String]
                    )

  case class EPCDetails(
                         lmkKey: String,
                         buildingReferenceNumber: Option[String],
                         currentEnergyRating: Option[String],
                         potentialEnergyRating: Option[String],
                         currentEnergyEfficiency: Option[String],
                         potentialEnergyEfficiency: Option[String],
                         propertyType: Option[String],
                         builtForm: Option[String],
                         inspectionDate: Date,
                         localAuthority: Option[String],
                         constituency: Option[String],
                         county: Option[String],
                         lodgementDate: Date,
                         transactionType: Option[String],
                         environmentImpactCurrent: Option[String],
                         environmentImpactPotential: Option[String],
                         energyConsumptionCurrent: Option[String],
                         energyConsumptionPotential: Option[String],
                         co2EmissionsCurrent: Option[String],
                         co2EmissCurrPerFloorArea: Option[String],
                         co2EmissionsPotential: Option[String],
                         lightingCostCurrent: Option[String],
                         lightingCostPotential: Option[String],
                         heatingCostCurrent: Option[String],
                         heatingCostPotential: Option[String],
                         hotWaterCostCurrent: Option[String],
                         hotWaterCostPotential: Option[String],
                         totalFloorArea: Option[Double],
                         energyTariff: Option[String],
                         mainsGasFlag: Option[String],
                         floorLevel: Option[String],
                         flatTopStorey: Option[String],
                         flatStoreyCount: Option[String],
                         mainHeatingControls: Option[String],
                         multiGlazeProportion: Option[String],
                         glazedType: Option[String],
                         glazedArea: Option[String],
                         extensionCount: Option[String],
                         numberHabitableRooms: Option[String],
                         numberHeatedRooms: Option[String],
                         lowEnergyLighting: Option[String],
                         numberOpenFireplaces: Option[String],
                         hotwaterDescription: Option[String],
                         hotWaterEnergyEff: Option[String],
                         hotWaterEnvEff: Option[String],
                         floorDescription: Option[String],
                         floorEnergyEff: Option[String],
                         floorEnvEff: Option[String],
                         windowsDescription: Option[String],
                         windowsEnergyEff: Option[String],
                         windowsEnvEff: Option[String],
                         wallsDescription: Option[String],
                         wallsEnergyEff: Option[String],
                         wallsEnvEff: Option[String],
                         secondheatDescription: Option[String],
                         sheatingEnergyEff: Option[String],
                         sheatingEnvEff: Option[String],
                         roofDescription: Option[String],
                         roofEnergyEff: Option[String],
                         roofEnvEff: Option[String],
                         mainheatDescription: Option[String],
                         mainheatEnergyEff: Option[String],
                         mainheatEnvEff: Option[String],
                         mainheatcontDescription: Option[String],
                         mainheatcEnergyEff: Option[String],
                         mainheatcEnvEff: Option[String],
                         lightingDescription: Option[String],
                         lightingEnergyEff: Option[String],
                         lightingEnvEff: Option[String],
                         mainFuel: Option[String],
                         windTurbineCount: Option[String],
                         heatLossCorridor: Option[String],
                         unheatedCorridorLength: Option[String],
                         floorHeight: Option[String],
                         photoSupply: Option[String],
                         solarWaterHeatingFlag: Option[String],
                         mechanicalVentilation: Option[String],
                         address: Option[String],
                         localAuthorityLabel: Option[String],
                         constituencyLabel: Option[String],
                         posttown: Option[String],
                         constructionAgeBand: Option[String],
                         lodgementDatetime: Option[String],
                         tenure: Option[String],
                         fixedLightingOutletsCount: Option[String],
                         lowEnergyFixedLightCount: Option[String]
                       )
}
